//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.13 at 05:35:43 PM CST 
//


package com.encora.choice.core.ws.hotelcatalog;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.encora.choice.core.ws.hotelcatalog package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.encora.choice.core.ws.hotelcatalog
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CreateHotelResponse }
     * 
     */
    public CreateHotelResponse createCreateHotelResponse() {
        return new CreateHotelResponse();
    }

    /**
     * Create an instance of {@link RemoveAmenityRequest }
     * 
     */
    public RemoveAmenityRequest createRemoveAmenityRequest() {
        return new RemoveAmenityRequest();
    }

    /**
     * Create an instance of {@link GetHotelRequest }
     * 
     */
    public GetHotelRequest createGetHotelRequest() {
        return new GetHotelRequest();
    }

    /**
     * Create an instance of {@link HotelSearchResponse }
     * 
     */
    public HotelSearchResponse createHotelSearchResponse() {
        return new HotelSearchResponse();
    }

    /**
     * Create an instance of {@link HotelSearchRequest }
     * 
     */
    public HotelSearchRequest createHotelSearchRequest() {
        return new HotelSearchRequest();
    }

    /**
     * Create an instance of {@link AmenityDTO }
     * 
     */
    public AmenityDTO createAmenityDTO() {
        return new AmenityDTO();
    }

    /**
     * Create an instance of {@link HotelDTO }
     * 
     */
    public HotelDTO createHotelDTO() {
        return new HotelDTO();
    }

    /**
     * Create an instance of {@link DeleteHotelRequest }
     * 
     */
    public DeleteHotelRequest createDeleteHotelRequest() {
        return new DeleteHotelRequest();
    }

    /**
     * Create an instance of {@link CreateHotelRequest }
     * 
     */
    public CreateHotelRequest createCreateHotelRequest() {
        return new CreateHotelRequest();
    }

    /**
     * Create an instance of {@link GetHotelResponse }
     * 
     */
    public GetHotelResponse createGetHotelResponse() {
        return new GetHotelResponse();
    }

    /**
     * Create an instance of {@link UpdateHotelRequest }
     * 
     */
    public UpdateHotelRequest createUpdateHotelRequest() {
        return new UpdateHotelRequest();
    }

    /**
     * Create an instance of {@link AddAmenityRequest }
     * 
     */
    public AddAmenityRequest createAddAmenityRequest() {
        return new AddAmenityRequest();
    }

}
