//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.13 at 05:35:43 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.encora.com/choice/core/ws/hotelCatalog", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.encora.choice.core.ws.hotelcatalog;
