
package com.encora.choice.webapp.ws.client;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HotelCatalogPort", targetNamespace = "http://www.encora.com/choice/core/ws/hotelCatalog")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HotelCatalogPort {


    /**
     * 
     * @param createHotelRequest
     * @return
     *     returns com.encora.choice.webapp.ws.client.CreateHotelResponse
     */
    @WebMethod(operationName = "CreateHotel")
    @WebResult(name = "CreateHotelResponse", targetNamespace = "http://www.encora.com/choice/core/ws/hotelCatalog", partName = "CreateHotelResponse")
    public CreateHotelResponse createHotel(
        @WebParam(name = "CreateHotelRequest", targetNamespace = "http://www.encora.com/choice/core/ws/hotelCatalog", partName = "CreateHotelRequest")
        CreateHotelRequest createHotelRequest);

    /**
     * 
     * @param updateHotelRequest
     */
    @WebMethod(operationName = "UpdateHotel")
    @Oneway
    public void updateHotel(
        @WebParam(name = "UpdateHotelRequest", targetNamespace = "http://www.encora.com/choice/core/ws/hotelCatalog", partName = "UpdateHotelRequest")
        UpdateHotelRequest updateHotelRequest);

    /**
     * 
     * @param addAmenityRequest
     */
    @WebMethod(operationName = "AddAmenity")
    @Oneway
    public void addAmenity(
        @WebParam(name = "AddAmenityRequest", targetNamespace = "http://www.encora.com/choice/core/ws/hotelCatalog", partName = "AddAmenityRequest")
        AddAmenityRequest addAmenityRequest);

    /**
     * 
     * @param deleteHotelRequest
     */
    @WebMethod(operationName = "DeleteHotel")
    @Oneway
    public void deleteHotel(
        @WebParam(name = "DeleteHotelRequest", targetNamespace = "http://www.encora.com/choice/core/ws/hotelCatalog", partName = "DeleteHotelRequest")
        DeleteHotelRequest deleteHotelRequest);

    /**
     * 
     * @param hotelSearchRequest
     * @return
     *     returns com.encora.choice.webapp.ws.client.HotelSearchResponse
     */
    @WebMethod(operationName = "HotelSearch")
    @WebResult(name = "HotelSearchResponse", targetNamespace = "http://www.encora.com/choice/core/ws/hotelCatalog", partName = "HotelSearchResponse")
    public HotelSearchResponse hotelSearch(
        @WebParam(name = "HotelSearchRequest", targetNamespace = "http://www.encora.com/choice/core/ws/hotelCatalog", partName = "HotelSearchRequest")
        HotelSearchRequest hotelSearchRequest);

    /**
     * 
     * @param getHotelRequest
     * @return
     *     returns com.encora.choice.webapp.ws.client.GetHotelResponse
     */
    @WebMethod(operationName = "GetHotel")
    @WebResult(name = "GetHotelResponse", targetNamespace = "http://www.encora.com/choice/core/ws/hotelCatalog", partName = "GetHotelResponse")
    public GetHotelResponse getHotel(
        @WebParam(name = "GetHotelRequest", targetNamespace = "http://www.encora.com/choice/core/ws/hotelCatalog", partName = "GetHotelRequest")
        GetHotelRequest getHotelRequest);

    /**
     * 
     * @param removeAmenityRequest
     */
    @WebMethod(operationName = "RemoveAmenity")
    @Oneway
    public void removeAmenity(
        @WebParam(name = "RemoveAmenityRequest", targetNamespace = "http://www.encora.com/choice/core/ws/hotelCatalog", partName = "RemoveAmenityRequest")
        RemoveAmenityRequest removeAmenityRequest);

}
