
package com.encora.choice.webapp.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HotelCatalogPortService", targetNamespace = "http://www.encora.com/choice/core/ws/hotelCatalog", wsdlLocation = "http://localhost:8080/ws/hotelCatalog.wsdl")
public class HotelCatalogPortService
    extends Service
{

    private final static URL HOTELCATALOGPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException HOTELCATALOGPORTSERVICE_EXCEPTION;
    private final static QName HOTELCATALOGPORTSERVICE_QNAME = new QName("http://www.encora.com/choice/core/ws/hotelCatalog", "HotelCatalogPortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ws/hotelCatalog.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HOTELCATALOGPORTSERVICE_WSDL_LOCATION = url;
        HOTELCATALOGPORTSERVICE_EXCEPTION = e;
    }

    public HotelCatalogPortService() {
        super(__getWsdlLocation(), HOTELCATALOGPORTSERVICE_QNAME);
    }

    public HotelCatalogPortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HOTELCATALOGPORTSERVICE_QNAME, features);
    }

    public HotelCatalogPortService(URL wsdlLocation) {
        super(wsdlLocation, HOTELCATALOGPORTSERVICE_QNAME);
    }

    public HotelCatalogPortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HOTELCATALOGPORTSERVICE_QNAME, features);
    }

    public HotelCatalogPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HotelCatalogPortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HotelCatalogPort
     */
    @WebEndpoint(name = "HotelCatalogPortSoap11")
    public HotelCatalogPort getHotelCatalogPortSoap11() {
        return super.getPort(new QName("http://www.encora.com/choice/core/ws/hotelCatalog", "HotelCatalogPortSoap11"), HotelCatalogPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HotelCatalogPort
     */
    @WebEndpoint(name = "HotelCatalogPortSoap11")
    public HotelCatalogPort getHotelCatalogPortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.encora.com/choice/core/ws/hotelCatalog", "HotelCatalogPortSoap11"), HotelCatalogPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HOTELCATALOGPORTSERVICE_EXCEPTION!= null) {
            throw HOTELCATALOGPORTSERVICE_EXCEPTION;
        }
        return HOTELCATALOGPORTSERVICE_WSDL_LOCATION;
    }

}
